/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "JWTSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RedisUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TodoFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "TodoRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}